server:
  port: 8081

spring:
  application:
    name: auth-service
#  security:
#    user:
#      name: admin
#      password: admin123

  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5433/auth_db}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:India@123}

  jpa:
    hibernate:
     ddl-auto: ${SPRING_JPA_HIBERNATE_DDL_AUTO:update}
    show-sql: true


eureka:
  client:
    register-with-eureka: false
    fetch-registry: false

logging:
  level:
    org.springframework.security: DEBUG
    com.ecommerce.auth: DEBUG

jwt:
  secret: ${JWT_SECRET:mysupersecuresecretkeymustbeatleast32chsdfwe2vs121cc4233d3arsl33434dong12345678Ab834bsj3jbji859439vj}
  expiration: ${JWT_EXPIRATION:3600000}
  access-expiration: ${JWT_ACCESS_EXPIRATION:700000}
  refresh-expiration: ${JWT_REFRESH_EXPIRATION:9000000}



#spring:
#  datasource:
#    url: jdbc:postgresql://localhost:5433/auth_db
#    username: postgres
#    password: India@123
#    driver-class-name: org.postgresql.Driver
#
#  jpa:
#    hibernate:
#      ddl-auto: ${SPRING_JPA_HIBERNATE_DDL_AUTO:update}
#      database: postgresql
#      database-platform: org.hibernate.dialect.PostgreSQLDialect
#    properties:
#      hibernate:
#        format_sql: true

#  cache:
#    jcache:
#      config: classpath:ehcache.xml
#
#  app:
#    jwtSecret: mySecretKey123912738aopsgjnspkmndfsopkvajoirjg94gf2opfng2moknm
#    jwtExpirationMs: 3000000
#    jwtCookieName: springBootEcom
#
#  ecom:
#    app:
#      jwtCookieName: springBootEcom
#
#  springfox:
#    documentation:
#      swagger-ui:
#        enabled: true
#
#server:
#  port: 10070
#
#logging:
#  level:
#    org.springframework.cache: TRACE
#    com.example.auth: DEBUG
#    org.hibernate.SQL: DEBUG
